name: newman tests execution
on:
  workflow_dispatch:
  push: 
    branches: [main] 
jobs:
  test: 
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./tests
    environment: dev
    steps:
      - name: Pull code
        uses: actions/checkout@v2
        
      - name: Set up Node
        uses: actions/setup-node@v2
        with: 
          node-version: "18.x"
      
      - name: Install dependencies
        run: "npm ci"
      
      - name: "Trigger tests"
        run: node tests/test-runner.js
      
      - name: Save report artifacg
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: newman-report
          path: './tests/report/'
          file_name: 'report.html'
          retention-days: 7
